# Type stubs for mail.client.doctype.mail_message.mail_message
from typing import Any

class MailMessage:
    name: str
    owner: str
    mail_queue_name: str
    
    def submit(self, scheduled_at: str | None = None) -> Any: ...
    def save(self) -> Any: ...
    def save_as_draft(self) -> Any: ...
    def update_attachments(self, attachments: list) -> Any: ...
