# Type stubs for frappe framework
from typing import Any, Callable

# Core frappe attributes
db: Any
session: Any
conf: Any
flags: Any

# Core functions
def whitelist(allow_guest: bool = False, methods: list[str] | None = None) -> Callable: ...
def throw(msg: str, exc: type | None = None) -> None: ...
def get_doc(doctype: str, name: str | None = None) -> Any: ...
def get_all(doctype: str, **kwargs: Any) -> list[dict]: ...
def log_error(title: str, message: str | None = None) -> None: ...
def get_traceback(with_context: bool = False) -> str: ...
def logger() -> Any: ...
def ready(fn: Callable) -> Callable: ...

# Translation function
def _(msg: str) -> str: ...

# Exceptions
class ValidationError(Exception): ...

# Utils namespace
class utils:
    @staticmethod
    def get_datetime(dt: str | None = None) -> Any: ...
    @staticmethod
    def now_datetime() -> Any: ...
    
    class datetime:
        @staticmethod
        def timedelta(**kwargs: Any) -> Any: ...
